/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Principal;

import java.applet.AudioClip;
import java.io.File;
import java.util.ArrayList;
import javax.swing.DefaultListModel;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileFilter;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author Rolando
 */
public class Menu extends javax.swing.JFrame {

    /**
     * Creates new form Menu
     */
    public Menu() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jd_crear_artista = new javax.swing.JDialog();
        jLabel2 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jLabel4 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        buttonGroup1 = new javax.swing.ButtonGroup();
        menu_popup = new javax.swing.JPopupMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jToolBar1 = new javax.swing.JToolBar();
        jb_agregar = new javax.swing.JButton();
        jb_editar = new javax.swing.JButton();
        jb_eliminar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        Fondo = new javax.swing.JLabel();

        jd_crear_artista.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Nombre:");
        jd_crear_artista.getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, -1, -1));

        jTextField1.setBackground(new java.awt.Color(255, 255, 255));
        jTextField1.setForeground(new java.awt.Color(0, 0, 0));
        jd_crear_artista.getContentPane().add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 50, 80, -1));

        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Publicacion:");
        jd_crear_artista.getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, -1, -1));
        jd_crear_artista.getContentPane().add(jDateChooser1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 90, -1, -1));

        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Genero:");
        jd_crear_artista.getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, -1, -1));

        jTextField2.setBackground(new java.awt.Color(255, 255, 255));
        jTextField2.setForeground(new java.awt.Color(0, 0, 0));
        jd_crear_artista.getContentPane().add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 130, 80, -1));

        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Formato:");
        jd_crear_artista.getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 170, -1, -1));

        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("Productor");
        jd_crear_artista.getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 210, -1, -1));

        jTextField3.setBackground(new java.awt.Color(255, 255, 255));
        jTextField3.setForeground(new java.awt.Color(0, 0, 0));
        jd_crear_artista.getContentPane().add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 210, 80, -1));

        buttonGroup1.add(jRadioButton1);
        jRadioButton1.setSelected(true);
        jRadioButton1.setText("Digital");
        jd_crear_artista.getContentPane().add(jRadioButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 170, -1, -1));

        buttonGroup1.add(jRadioButton2);
        jRadioButton2.setText("Fisico");
        jd_crear_artista.getContentPane().add(jRadioButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 170, -1, -1));

        jButton1.setText("Crear Album");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        jd_crear_artista.getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 250, -1, -1));

        jButton2.setText("Añadir cancion");
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });
        jd_crear_artista.getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 220, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Principal/amarillo-1200x839.png"))); // NOI18N
        jd_crear_artista.getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 500, 300));

        jMenuItem1.setText("jMenuItem1");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        menu_popup.add(jMenuItem1);

        jMenuItem2.setText("jMenuItem2");
        menu_popup.add(jMenuItem2);

        jMenuItem3.setText("jMenuItem3");
        menu_popup.add(jMenuItem3);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jToolBar1.setRollover(true);

        jb_agregar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Principal/add-file.jpg"))); // NOI18N
        jb_agregar.setFocusable(false);
        jb_agregar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jb_agregar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jb_agregar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_agregarMouseClicked(evt);
            }
        });
        jToolBar1.add(jb_agregar);

        jb_editar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Principal/edit_file.jpg"))); // NOI18N
        jb_editar.setFocusable(false);
        jb_editar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jb_editar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(jb_editar);

        jb_eliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Principal/delete_file.jpg"))); // NOI18N
        jb_eliminar.setFocusable(false);
        jb_eliminar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jb_eliminar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(jb_eliminar);

        getContentPane().add(jToolBar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 180, 40));

        jList1.setModel(new DefaultListModel());
        jList1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jList1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jList1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, 110, -1));

        Fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Principal/color_verde.jpg"))); // NOI18N
        getContentPane().add(Fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 500, 300));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jb_agregarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_agregarMouseClicked
        // TODO add your handling code here:
        jd_crear_artista.setModal(true);
        jd_crear_artista.pack();
        jd_crear_artista.setLocationRelativeTo(this);
        jd_crear_artista.setVisible(true);
    }//GEN-LAST:event_jb_agregarMouseClicked

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        // TODO add your handling code here:
        album A = new album();
        A.setNombre(jTextField1.getText());
        A.setPublicacion(jDateChooser1.getDate());
        if (jRadioButton1.isSelected()){
            A.setFormato("Digital");
        }
        if (jRadioButton2.isSelected()){
            A.setFormato("Fisico");
        }
        A.setProductor(jTextField3.getText());
        albumes.add(A);
    }//GEN-LAST:event_jButton1MouseClicked

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
        // TODO add your handling code here:
        if (albumes.isEmpty()){
            JOptionPane.showMessageDialog(jd_crear_artista, "No hay ningun album, cree uno");
        }
        else{
            String nombre = JOptionPane.showInputDialog(jd_crear_artista, "Nombre de la cancion");
            int duracion = Integer.parseInt(JOptionPane.showInputDialog(jd_crear_artista, "Duracion de la cancion (en segundos)"));
            String composotor = JOptionPane.showInputDialog(jd_crear_artista, "nombre del compositor");
            String distribuidor = JOptionPane.showInputDialog(jd_crear_artista, "nombre del distribuidor");
            String exclusiva = JOptionPane.showInputDialog(jd_crear_artista, "Exclusiva de spotify?[s/n]");
            String productor = JOptionPane.showInputDialog(jd_crear_artista, "nombre del productor");
            String invitado = JOptionPane.showInputDialog(jd_crear_artista, "nombre del invitado (si no hay ninguno deje en blanco)");
            cancion C = new cancion();
            C.setNombre(nombre);
            C.setDuracion(duracion);
            C.setCompositor(composotor);
            C.setDistribuidor(distribuidor);
            C.setExclusiva(exclusiva);
            C.setProductor(productor);
            C.setInvitado(invitado);
            JFileChooser fc = new JFileChooser();
            FileFilter filtro = new FileNameExtensionFilter("Audio","mp3","mp4","wma");
            fc.setFileFilter(filtro);
            File archivo;
            int op = fc.showOpenDialog(jd_crear_artista);
            if (op==JFileChooser.APPROVE_OPTION){
                archivo = fc.getSelectedFile();
                C.setArchivo(archivo);
            }
            canciones.add(C);
            DefaultListModel modelo = (DefaultListModel)jList1.getModel();
            modelo.addElement(C);
            String a = JOptionPane.showInputDialog(jd_crear_artista, "nombre del album al cual se va a agregar");
            for (int i = 0; i < albumes.size(); i++) {
                String n = albumes.get(i).getNombre();
                if (n.equalsIgnoreCase(a)){
                    albumes.get(i).setCanciones(C);
                }
            }
        }
    }//GEN-LAST:event_jButton2MouseClicked

    private void jList1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jList1MouseClicked
        // TODO add your handling code here:
        if (evt.isMetaDown()){
            if (jList1.getSelectedIndex()>=0){
                menu_popup.show(evt.getComponent(), evt.getX(), evt.getY());
            }
        }
    }//GEN-LAST:event_jList1MouseClicked

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        sonido audio = new sonido();
        File archivo = null;
        String m = jList1.getSelectedValue();
        for (int i = 0; i < canciones.size(); i++) {
            if (canciones.get(i).toString().equals(m)){
                archivo = canciones.get(i).getArchivo();
            }
        }
        AudioClip musica = audio.getAudio(archivo.getPath());
        try{
            musica.play();
        }
        catch(Exception e){
            musica.stop();
            musica.play();
        }
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    ArrayList<album> albumes = new ArrayList();
    ArrayList<cancion> canciones = new ArrayList();
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Fondo;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JList<String> jList1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JButton jb_agregar;
    private javax.swing.JButton jb_editar;
    private javax.swing.JButton jb_eliminar;
    private javax.swing.JDialog jd_crear_artista;
    private javax.swing.JPopupMenu menu_popup;
    // End of variables declaration//GEN-END:variables
}
